--
-- Dump generated by PostgreSQL Anonymizer 1.1.0
--
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3 (Debian 14.3-1.pgdg110+1)
-- Dumped by pg_dump version 14.1 (Debian 14.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: FoO; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA "FoO";


ALTER SCHEMA "FoO" OWNER TO postgres;

--
--



--
--



--
--



--
--



--
-- Name: test_pg_dump_anon; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA test_pg_dump_anon;


ALTER SCHEMA test_pg_dump_anon OWNER TO postgres;

--
-- Name: BuG_298; Type: SEQUENCE; Schema: FoO; Owner: postgres
--

CREATE SEQUENCE "FoO"."BuG_298"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "FoO"."BuG_298" OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    id integer NOT NULL,
    name text,
    vat_id text
);


ALTER TABLE public.company OWNER TO postgres;

--
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.company_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.company_id_seq OWNER TO postgres;

--
-- Name: company_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.company_id_seq OWNED BY public.company.id;


--
-- Name: owner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.owner (
    firstname text
);


ALTER TABLE public.owner OWNER TO postgres;

--
-- Name: seq42; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq42
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq42 OWNER TO postgres;

--
-- Name: supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier (
    id integer NOT NULL,
    fk_company_id integer,
    contact text,
    phone text,
    job_title text
);


ALTER TABLE public.supplier OWNER TO postgres;

--
-- Name: supplier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.supplier_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.supplier_id_seq OWNER TO postgres;

--
-- Name: supplier_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.supplier_id_seq OWNED BY public.supplier.id;


--
-- Name: no_masks; Type: TABLE; Schema: test_pg_dump_anon; Owner: postgres
--

CREATE TABLE test_pg_dump_anon.no_masks (
    "?column?" integer
);


ALTER TABLE test_pg_dump_anon.no_masks OWNER TO postgres;

--
-- Name: three; Type: SEQUENCE; Schema: test_pg_dump_anon; Owner: postgres
--

CREATE SEQUENCE test_pg_dump_anon.three
    START WITH 3
    INCREMENT BY -1
    MINVALUE 1
    MAXVALUE 3
    CACHE 1
    CYCLE;


ALTER TABLE test_pg_dump_anon.three OWNER TO postgres;

--
-- Name: company id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company ALTER COLUMN id SET DEFAULT nextval('public.company_id_seq'::regclass);


--
-- Name: supplier id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier ALTER COLUMN id SET DEFAULT nextval('public.supplier_id_seq'::regclass);


--
-- PostgreSQL database dump complete
--



COPY public.company FROM STDIN WITH CSV;
952,Shadrach,FR62684255667
194,Johnny's Shoe Store,CHE670945644
346,Capitol Records,GB663829617823
\.


COPY public.owner FROM STDIN WITH CSV;
Robert
\.


COPY public.supplier FROM STDIN WITH CSV;
299,194,Johnny Ryall,597-500-569,CEO
157,346,George Clinton,131-002-530,Sales manager
\.


COPY test_pg_dump_anon.no_masks FROM STDIN WITH CSV;
1
\.

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3 (Debian 14.3-1.pgdg110+1)
-- Dumped by pg_dump version 14.1 (Debian 14.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: BuG_298; Type: SEQUENCE SET; Schema: FoO; Owner: postgres
--

SELECT pg_catalog.setval('"FoO"."BuG_298"', 298, false);


--
-- Name: company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.company_id_seq', 1, false);


--
-- Name: seq42; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq42', 42, false);


--
-- Name: supplier_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supplier_id_seq', 1, false);


--
-- Name: three; Type: SEQUENCE SET; Schema: test_pg_dump_anon; Owner: postgres
--

SELECT pg_catalog.setval('test_pg_dump_anon.three', 3, false);


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3 (Debian 14.3-1.pgdg110+1)
-- Dumped by pg_dump version 14.1 (Debian 14.1-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: company company_vat_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_vat_id_key UNIQUE (vat_id);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id);


--
-- Name: supplier supplier_fk_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_fk_company_id_fkey FOREIGN KEY (fk_company_id) REFERENCES public.company(id);


--
-- PostgreSQL database dump complete
--

